#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

(cd fluid && ./Allrun.pre)
(cd solid && runApplication blockMesh)
(cd solid && transformPoints -scale "(0.5 0.0035 0.0035)")
(cd solid && transformPoints -rollPitchYaw "(0 -90 0)")
(cd solid && runApplication topoSet)
(cd solid && runApplication createPatch -overwrite)

# (cd solid && runApplication snappyHexMesh -overwrite)
(cd solid && touch z.foam)
(cd fluid && touch z.foam)

# Run serial
# mpirun -app ./mpirun.schema

# Run parallel
(cd fluid && runApplication decomposePar)
(cd solid && runApplication decomposePar)

# mpirun -app ./mpirun.schema_parallel
# The problem is keeping the log files separate so use the openmpi
# mpirun option to keep the separate outputs in the logs/ directory

mpirun \
    --output-filename logs \
    -np 22 --oversubscribe compressiblePhaseChangeInterFoam -case fluid -world fluid -parallel : \
    -np 8 solidFoam -case solid -world solid -parallel \
    >& log.compressiblePhaseChangeInterFoam_solidFoam

#------------------------------------------------------------------------------
